### ISSUE TITLE
Potential Instructional Translations/Edits

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/mslearn-azure-ml.ja-jp#4]
Hi.  Attached are notes from a native Japanese QA.   I am merely presenting what I received in Japanese, in order to preserve anything that could be potentially lost in translation.  You might want to scan the contents and decide what, if anything, deems merit. 

[DP-100_QA.docx](https://github.com/MicrosoftLearning/mslearn-azure-ml.ja-jp/files/11480746/DP-100_QA.docx)

**Comment by chriscarty00** [comment]
Covered in https://dev.azure.com/ceapex/CEINTL/_workitems/edit/823115
